CREATE TABLE total_2015 (
  doi text CONSTRAINT firstkey PRIMARY KEY,
  article_title text,
  journal_full_title  text,
  issn_eissn text,
  period integer,
  is_gold boolean,
  is_hybrid boolean,
  is_green boolean,
  license text,
  non_oa boolean,
  bfi_level integer,
  publisher text,
  institution text,
  corresponding_university  text,
  valuta text,
  apc real,
  apc_year integer,
  apc_source  text,
  apc_url text,
  submission_fee  real,
  page_charge real,
  color_charge  real,
  ccby_charge real,
  institutional_discount  real,
  funding text,
  funding_text  text,
  invoice_valuta  text,
  invoice_amount  real,
  invoice_amount_discount real,
  other_charges real
);
